### ISSUE TITLE
[View Idea] A view to list/search/install/un-install views - yumView

### ISSUE THREAD

**Issue by sainib** [abajwa-hw/ambari-workshops#4]
The idea is to create a Maven-Central of Views as a View itself. So all the views that we have to offer are made available in some public repository and then this view can be installed as the first view..using which ambari users can search for available views (in the central public repository) or browse the list of views.. they should also be able to just install a view by clicking on install button next to a view. 

Lastly, they should be able to see the installed views (current functionality) and uninstall a view..

**Comment by abajwa-hw** [comment]
Check this https://github.com/jpplayer/amstore-view
